### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by larrycinnabar** [alexalexiuc/hats-for-parties-go#1]
1. minor (https://github.com/alexalexiuc/hats-for-parties-go/blob/master/app/router/router.go):
can you do routes a bit more RESTish?

2. major(https://github.com/alexalexiuc/hats-for-parties-go/blob/master/app/mongo/hats.go#L31):
solution for concurrent safety is a bit rough. Can you do it just via mongo?

**Comment by alexalexiuc** [comment]
> can you do routes a bit more RESTish?

Can you be more precise?

>  Can you do it just via mongo?

Well, yes. The only way I have found so far to implement this with mongo only is by using transactions, to make documents read & update atomic when finding available hats + updating for the party.
But I am struggling to set up a replica instance in docker of mongo to use transactions, only if there is another way that does not involve transactions.

**Comment by alexalexiuc** [comment]
> 1. minor (https://github.com/alexalexiuc/hats-for-parties-go/blob/master/app/router/router.go):
>    can you do routes a bit more RESTish?
> 2. major(https://github.com/alexalexiuc/hats-for-parties-go/blob/master/app/mongo/hats.go#L31):
>    solution for concurrent safety is a bit rough. Can you do it just via mongo?

@larrycinnabar 
Forget my previous message regarding the flag. It was a tough morning xD.
I implemented the same functionality using a MongoDB collection. I was overthinking it when built the initial solution.
See PR: https://github.com/alexalexiuc/hats-for-parties-go/pull/2

But still, I want to ask about the first note, re RESTfullnes. Could you please elaborate a bit on what exactly you think should be changed, or what is the issue?

**Comment by larrycinnabar** [comment]
hey. About (1), I mean that to replace your routes `POST /start-party` and `POST /end-party` to something more REST-idiomatic

**Comment by alexalexiuc** [comment]
> hey. About (1), I mean that to replace your routes `POST /start-party` and `POST /end-party` to something more REST-idiomatic

I see what you mean. Will change.

And re PR. Should I merge it, or you will let me know if it is ok to be merged?

**Comment by larrycinnabar** [comment]
Feel free to merge
